### ISSUE TITLE
User Page goes blank after logging in

### ISSUE THREAD

**Issue by peterkure3** [ottojoash/jochat#3]
When a user logs in, the chat page pops up and the page goes blank.

**Comment by ottojoash** [comment]
lets look at the onsumbit button and try to fix it and see where it redirects after a user submitting his credentials
![image](https://user-images.githubusercontent.com/34677630/214802932-460dee1a-ca4c-4f78-83ef-5e4019735e64.png)

**Comment by ottojoash** [comment]
error cause by firebase api for datastore in cloud fare 
![image](https://user-images.githubusercontent.com/34677630/214804795-d6915268-d542-4e93-a2af-a6ac725a5779.png)

**Comment by ottojoash** [comment]
fixed api key ..displaying home  page
